# Revisão da literatura

Os métodos de previsão geralmente usam valores do passado para fazer previsões de valores futuros. No início do século XIX, as previsões eram feitas recorrendo à extrapolação simples de um valor global, ajustado em função do tempo [@xavier2016analise]. Devido à incapacidade desses métodos solucionarem problemas mais complexos, foi necessário desenvolver métodos mais eficientes e capazes de produzir melhores resultados.

As séries temporais estão incluídas no domínio das probabilidades e estatística, mais concretamente, no campo dos processos estocásticos. O início dos anos 70, foi considerado como a época de ouro no desenvolvimento das séries temporais devido aos vários trabalhos feitos e às metodologias de análise e previsão desenvolvidas [@Estatcamp]. O trabalho de Box e Jenkins [@box1994pages] é considerado como uma obra de referência na história do desenvolvimento das séries temporais, pois ela integra os conhecimentos existentes sobre séries temporais até a data. Os autores apresentaram modelos estocásticos no domínio de séries temporais discretas com número mínimo de parâmetros, satisfazendo o princípio de parcimónia.


São muitos e diversos os trabalhos de investigação com aplicações de séries na economia e finanças. Numa pesquisa realizada nos Estados Unidos da América por Andrei et al. [-@andrei2011econometric], foram utilizadas séries temporais para se fazer a previsão do PIB dos EUA. Como a série encontrada não era estacionária, os autores usaram vários métodos estatísticos para a transformar numa série estacionária. Depois de aplicar os testes a série foi transformada numa estacionária e integrada de ordem 1. Os autores aplicaram a metodologia de *Box-Jenkins* para a determinação do ARMA (Auto-regressivos - Médias Móveis). Usando o método dos mínimos quadrados na determinação dos parâmetros, optou-se, nesse caso, pelo modelo $ARIMA(1, 1, 1)$ devido à melhor performance.

Num outro trabalho similar desenvolvido para a previsão do PIB do Brasil, a preços correntes [-@inproceedings], os autores usaram os modelos Holt-Winters multiplicativo, SARIMA e o modelo Linear Dinâmico para a previsão. Os dados compreendiam observações entre 1996 e 2019 (observações trimestrais). A observação da medida de U-Theil mostrou que os modelos precisavam se ajustar a períodos em que choques económicos significativos afetam o crescimento da economia brasileira. A série analisada e a previsão dos modelos apresentava a necessidade de um crescimento sustentado numa economia de mercado. Também se verificou que na série analisada, o modelo linear dinâmico apresentava melhor ajuste aos dados e um desempenho preditivo mais eficiente.

Baltac [-@baltac2015economic], num pequeno artigo, estudou a possibilidade de usar séries temporais para fazer uma análise económica e financeira, usando como indicador principal o *turnover*(indicador do grau de liquidez dos ativos de uma empresa, ou seja, a capacidade de uma empresa gerar receitas usando os seus ativos). No trabalho, foi realizado um estudo prático, onde foi analisada a evolução do *turnover* extraído do balanço de uma empresa da Roménia, no período de 2004 a 2014. Usando séries temporais a autora determinou a previsão de crescimento da empresa.

Numa pesquisa sobre a previsão do crescimento económico na região de Shenzhen na China usando séries temporais [@wang2016forecast], o autor usou o modelo $ARIMA(3, 3, 5)$, pois segundo ele é o que melhor reflete a lei do desenvolvimento económico, e pode ser usado para previsão a médio e a longo prazo. Chegou-se à conclusão de que num espaço de 5 anos, a região em estudo experimentaria uma tendência de crescimento lento.

Através de uma pesquisa empírica realizada por Zhenwei et al. [-@li2020forecasting], concluiu-se que o modelo ARIMA tradicional tem uma variância muito grande na previsão de séries temporais financeiras com alta frequência. Com a melhoria da capacidade de computação, os autores chegaram a conclusão que juntando o método ARIMA tradicional com a tecnologia *deep learning* pode-se melhorar nas previsões de tais séries. No seu estudo, o autor usou como série temporal o índice CSI300 da Bolsa de Valores de Shanghai.

Stock [-@inbook] numa pesquisa mais teórica, apresentou várias especificidades de séries temporais e a sua aplicação na economia. No estudo foi apresentado as séries temporais univariáveis e multivariáveis, detalhes a considerar na escolha de modelos, dificuldades habitualmente encontrados nas previsões, instabilidades dos modelos e possíveis falhas nos modelos.

Um aspeto a ter em conta na modelação  estacionária de séries temporais segundo Lopes [-@Lopes2008], tem a ver com a sazonalidade dos dados. Por exemplo, segundo a autora, para certas séries mensais os dados relativos a um mesmo mês em diferentes anos têm tendência a situar-se de maneira semelhante em relação à média anual. Uma maneira de solucionar esse problema segundo a autora é aplicar a metodologia $SARIMA$ (a letra S vem do temo *sazonal*), desenvolvida por Box e Jenkins, capaz de ter em conta a sazonalidade dos dados. O princípio subjacente a esse modelo, é a aplicação do modelo $ARIMA$, após a eliminação da sazonalidade.


