on:
  push:
    branches: master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      # renv::init() # must have been run prior to this
      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      # if not using renv # run: R -e 'install.packages(c("tidyverse", "kableExtra", "bookdown"))'
      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      # Setup TinyTeX - for pdf output 
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Build all bookdown outputs
        run: | 
          # Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
          Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # git commit -m "Add changes" -a
          git add -A && git commit -m "Add changes" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
